"""empty message

Revision ID: 831369b0ceb0
Revises: 9d6b38b7b023
Create Date: 2026-02-11 03:40:48.751431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '831369b0ceb0'
down_revision: Union[str, Sequence[str], None] = '9d6b38b7b023'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'refresh_token', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_token', type_='unique')
    # ### end Alembic commands ###
